services:

  # --------------------
  # DATABASE (PostgreSQL)
  # --------------------
  db:
    image: postgres:15
    container_name: nexthire-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nexthire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # --------------------
  # REDIS (for caching + celery)
  # --------------------
  redis:
    image: redis:7
    container_name: nexthire-redis
    restart: always
    ports:
      - "6379:6379"

  # --------------------
  # BACKEND (FastAPI)
  # --------------------
  backend:
    build: ./backend
    container_name: nexthire-backend
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nexthire
      REDIS_URL: redis://redis:6379/0
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend:/app

  # --------------------
  # CELERY WORKER
  # --------------------
  worker:
    build: ./backend
    container_name: nexthire-worker
    restart: always
    depends_on:
      - backend
      - redis
      - db
    command: celery -A tasks.celery_app worker --loglevel=info
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/nexthire
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ./backend:/app

  # --------------------
  # FRONTEND (static HTML/CSS/JS)
  # --------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
    container_name: nexthire-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5500:80"

# --------------------
# VOLUMES
# --------------------
volumes:
  pgdata:
